---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    # Certainly we can use these somewhere
    - set_fact:
        os_name: "{{ ansible_distribution }}"
        os_ver: "{{ ansible_distribution_major_version }}"
  tasks:
    