---
- hosts: localhost
  connection: local

  pre_tasks:
    # Certainly we can use these somewhere
    - set_fact:
        os_name: "{{ ansible_distribution }}"
        os_ver: "{{ ansible_distribution_major_version }}"
  tasks:
    - name: Get Current Kvantum Manager Version
      shell: kvantummanager --version
      register: kvantum_sys_version