---
- hosts: localhost
  connection: local
  become: true

####### DEFINING VARIABLES AND SUCH ################################################
  vars_files:
    - vars/ssh-tunneling.yml

  pre_tasks:
    # Certainly we can use these somewhere
    - set_fact:
        os_name: "{{ ansible_distribution }}"
        os_ver: "{{ ansible_distribution_major_version }}"

########### BASIC CONFIGURATION (basic_setup) ######################################
  tasks:
    - block:
      - stat: path=vars/hosts/{{ ansible_hostname }}.yml
        register: host_vars_file

      - name: Include Host specific vars (if exists)
        include_vars:
          file: hosts/{{ ansible_hostname }}.yml
        when: host_vars_file.stat.exists

      - name: Ensure the local system has a proper hostname
        hostname: name="{{ sys_hostname }}"
  
      - name: Ensure there is an .ssh directory
        file:
          path: "/home/{{ sys_user }}/.ssh"
          state: directory
          owner: "{{ sys_user }}"
          group: "{{ sys_user }}" 
          mode: 0700
  
      - name: Ensure local system ssh-configuration is up to date
        template:
          dest: "/home/{{ sys_user }}/.ssh/config"
          src: templates/ssh-config.j2
          owner: "{{ sys_user }}"
          group: "{{ sys_user }}"
          mode: 0644

########### INITIAL PACKAGE UPDATES AND INSTALLS (basic_updates) ###################
    - block:
      - include: tasks/repos.yml
      - include: tasks/update-system.yml
      - include: tasks/common-packages.yml
      # - include: tasks/snap.yml

      - name: Make sure local system has additional third-party packages present and up to date
        dnf:
          name: "{{ dnf_extras }}"
          state: latest
        when: dnf_extras is defined

      - include: tasks/sudoers.yml
      - include: tasks/cron.yml
      - include: tasks/sysctl.yml
      - include: tasks/users.yml
      - include: tasks/services.yml
      - include: tasks/firewalld.yml
      - include: tasks/timezone.yml
      # - include: tasks/nsswitch.yml

########### CONFIGURE PROFILES AND OTHER ODDITIES ABOUT THIS SYSTEM (basic_config) #
    - block:
      - name: Make sure the Git profile is up to date
        template:
          dest: "/home/{{ sys_user }}/.gitconfig"
          src: templates/gitconfig.j2
          owner: "{{ sys_user }}"
          group: "{{ sys_user }}"
