---
- hosts: localhost
  connection: local
  roles:
    - common

####### DEFINING VARIABLES AND SUCH ################################################
  vars_files:
    - vars/ssh-tunneling.yml
    - vars/common.yml

  pre_tasks:
    # Certainly we can use these somewhere
    - set_fact:
        os_name: "{{ ansible_distribution }}"
        os_ver: "{{ ansible_distribution_major_version }}"

########### BASIC CONFIGURATION (basic_setup) ######################################
  tasks:
    - block:
      - stat: path=vars/hosts/{{ ansible_hostname }}.yml
        register: host_vars_file

      - name: Include Host specific vars (if exists)
        include_vars:
          file: hosts/{{ ansible_hostname }}.yml
        when: host_vars_file.stat.exists
