---
- name: Install Snap Packages
  command: 'snap install "{{ item }}"'
  with_items:
    - mailspring

# - name: Install Classic Snap Packages
#   command: 'snap install "{{ item }}" --classic'
#   with_items:
#     - restic