---
- name: Ensure there is an .ssh directory
  file:
    path: "/home/{{ sys_user }}/.ssh"
    state: directory
    owner: "{{ sys_user }}"
    group: "{{ sys_user }}"
    mode: 0700

- name: Fixing SSH Key Permissions
  file:
    path: "/home/{{ sys_user }}/.ssh"
    recurse: yes
    owner: "{{ sys_user }}"
    group: "{{ sys_user }}"
    mode: 0600

- name: Fixing SSH Key Permissions
  file:
    path: "/home/{{ sys_user }}/.ssh"
    owner: "{{ sys_user }}"
    group: "{{ sys_user }}"
    mode: 0700

- name: Ensure local system ssh-configuration is up to date
  template:
    dest: "/home/{{ sys_user }}/.ssh/config"
    src: templates/ssh-config.j2
    owner: "{{ sys_user }}"
    group: "{{ sys_user }}"
    mode: 0644

- name: Install GitHub SSH Pub Keys
  authorized_key:
    user: "{{ sys_user }}"
    state: present
    key: https://github.com/{{item}}.keys
  with_items:
    - computerfr33k

- name: Make sure the Git profile is up to date
  template:
    dest: "/home/{{ sys_user }}/.gitconfig"
    src: templates/gitconfig.j2
    owner: "{{ sys_user }}"
    group: "{{ sys_user }}"