---
- hosts: localhost
  connection: local
  become: true

####### DEFINING VARIABLES AND SUCH ################################################
  vars_files:
    - ../vars/ssh-tunneling.yml

  pre_tasks:
    # Certainly we can use these somewhere
    - set_fact:
        os_name: "{{ ansible_distribution }}"
        os_ver: "{{ ansible_distribution_major_version }}"

########### BASIC CONFIGURATION (basic_setup) ######################################
  tasks:
    - block:
      - name: Ensure the local system has a proper hostname
        hostname: name="{{ sys_hostname }}"
  
      - name: Ensure there is an .ssh directory
        file:
          path: "/home/{{ sys_user }}/.ssh"
          state: directory
          owner: "{{ sys_user }}"
          group: "{{ sys_user }}" 
          mode: 0700
  
      - name: Ensure local system ssh-configuration is up to date
        template:
          dest: "/home/{{ sys_user }}/.ssh/config"
          src: ../templates/ssh-config.j2
          owner: "{{ sys_user }}"
          group: "{{ sys_user }}"
          mode: 0644

########### INITIAL PACKAGE UPDATES AND INSTALLS (basic_updates) ###################
    - block:
      - include: repos.yml
      - include: update-system.yml
      - include: common-packages.yml

      - name: Make sure local system has additional third-party packages present and up to date
        dnf:
          name: "{{ dnf_extras }}"
          state: latest
        when: dnf_extras is defined

      - include: cron.yml

########### CONFIGURE PROFILES AND OTHER ODDITIES ABOUT THIS SYSTEM (basic_config) #
    - block:
      - name: Ensure there is a docker group
        group:
          name: docker

      - name: Ensure there is a vboxusers group
        group:
          name: vboxusers
      
      - name: Ensure the system user belongs to the docker, vboxusers and wheel groups
        user:
          name: "{{ sys_user }}"
          groups: docker,wheel,vboxusers
          append: yes
          state: present

      - name: Make sure the Git profile is up to date
        template:
          dest: "/home/{{ sys_user }}/.gitconfig"
          src: ../templates/gitconfig.j2
          owner: "{{ sys_user }}"
          group: "{{ sys_user }}"

      - include: services.yml
