---
- name: Remove Pre-installed Packages
  dnf:
    name: '{{ remove_packages }}'
    state: absent
  vars:
    remove_packages:
      - ktorrent
      - kget
      - akregator
      - konversation
      - kmail
      - krdc
      - falkon
      - konqueror
      - kamoso
      - juk
      - dragon
      - "calligra-*"
      - mediawriter
      - krusader
      - kmag
      - kmouth

- name: Autoremove Packages
  dnf:
    autoremove: yes

- name: Install RPM Fusion
  dnf:
    name: '{{ install_packages }}'
    state: latest
  vars:
    install_packages:
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ os_ver }}.noarch.rpm
      - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ os_ver }}.noarch.rpm

- name: Install Common Packages (for all machines)
  dnf:
    name: '{{ install_packages }}'
    state: latest
  vars:
    install_packages:
      - acpid
      - balena-etcher-electron
      - bzip2
      - code
      - docker-ce
      - ffmpegthumbs
      - fish
      - gcc
      - git
      - google-roboto-fonts
      - hplip-gui
      - htop
      - insync
      - keepassxc
      - libreoffice-icon-theme-papirus
      - materia-theme
      - mediainfo-qt
      - mozilla-fira-mono-fonts
      - papirus-icon-theme
      - powerline
      - powerline-fonts
      - rclone
      - rcm
      - remmina
      - restic
      - rsync
      - syncthing
      - syncthing-gtk
      - timeshift
      - tree
      - unzip
      - vim
      - VirtualBox-6.0
      - yarn
      - yubioath-desktop
      - zip

- name: Cleanup Kvantum Build
  file:
    state: absent
    path: /tmp/kvantum-build/

- name: Get Current Kvantum Manager Version
  shell: kvantummanager --version
  register: kvantum_sys_version

- set_fact:
    installed_kvantum_version: "V{{ kvantum_sys_version.stdout | regex_replace('^Kvantum Manager (.*)$', '\\1') }}"

- include: install-kvantum-manager.yml
  when: installed_kvantum_version != "V0.10.8"
