---
- block:
  - include: tasks/repos.yml
  - include: tasks/update-system.yml
  - include: tasks/common-packages.yml
  - include: tasks/snap.yml
  - include: tasks/extra-packages.yml
  - include: tasks/sudoers.yml
  - include: tasks/cron.yml
  - include: tasks/sysctl.yml
  - include: tasks/users.yml
  - include: tasks/services.yml
  - include: tasks/firewalld.yml
  - include: tasks/timezone.yml
  become: yes