---
- name: Ensure there is an .ssh directory
  file:
    path: "/home/{{ sys_user }}/.ssh"
    state: directory
    owner: "{{ sys_user }}"
    group: "{{ sys_user }}"
    mode: 0700

- name: Fixing SSH Key Permissions
  file:
    path: "/home/{{ sys_user }}/.ssh"
    recurse: yes
    owner: "{{ sys_user }}"
    group: "{{ sys_user }}"
    mode: 0600

- name: Fixing SSH Key Permissions
  file:
    path: "/home/{{ sys_user }}/.ssh"
    owner: "{{ sys_user }}"
    group: "{{ sys_user }}"
    mode: 0700

- name: Fixing SSH Public Key Permissions
  file:
    path: "/home/{{ sys_user }}/.ssh/{{ default_identity_key_file }}.pub"
    owner: "{{ sys_user }}"
    group: "{{ sys_user }}"
    mode: 0644

- name: Ensure local system ssh-configuration is up to date
  template:
    dest: "/home/{{ sys_user }}/.ssh/config"
    src: templates/ssh-config.j2
    owner: "{{ sys_user }}"
    group: "{{ sys_user }}"
    mode: 0644

- name: Install GitHub SSH Pub Keys
  authorized_key:
    user: "{{ sys_user }}"
    state: present
    key: https://github.com/{{item}}.keys
  with_items:
    - computerfr33k

- name: Make sure the Git profile is up to date
  template:
    dest: "/home/{{ sys_user }}/.gitconfig"
    src: templates/gitconfig.j2
    owner: "{{ sys_user }}"
    group: "{{ sys_user }}"

- name: Add User to Docker Group
  user:
    name: "{{ sys_user }}"
    shell: /bin/bash
    groups: docker
    append: yes

- block:
  - include: kde-configs.yml

  - name: Deploy Dotfiles
    git:
        repo: 'git@gitlab.com:computerfr33k/dotfiles.git'
        dest: "{{ '~' | expanduser }}/.dotfiles"
        key_file: "{{ '~' | expanduser }}/.ssh/{{ default_identity_key_file }}"
        accept_hostkey: yes
    register: rcm_repo

  - name: update and install dotfiles managed by rcm
    shell: rcup
    when: rcm_repo.changed
  become: yes
  become_method: su
  become_user: "{{ sys_user }}"
  
